FROM node:latest
RUN apt install -y  bzip2 git
RUN npm install -g @angular/cli


RUN apt update -y
RUN apt install -y apt-transport-https

RUN curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
RUN apt update -y

RUN  apt  install -y  google-chrome-stable --no-install-recommends
